services:
  github-runner:
    image: myoung34/github-runner:ubuntu-jammy
    container_name: local-github-runner
    environment:
      # The full URL to your repository (or organization)
      - REPO_URL=https://github.com/24may/aks-argo
      # - RUNNER_EPHEMERAL=true
      # Use either RUNNER_TOKEN or ACCESS_TOKEN (Read Step 2 below)
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      
      - RUNNER_NAME=docker-local-runner
      - RUNNER_WORKDIR=/tmp/runner/work
      - RUNNER_GROUP=Default
      - LABELS=aks-argo,terraform
      
      # Optional: If your workflows build Docker images, you need this
      # to pass your host machine's Docker engine into the runner.
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      # Bind the Docker socket to allow Docker-in-Docker operations
      - /var/run/docker.sock:/var/run/docker.sock
      # Bind a local directory to inspect files if a job fails
      - ./runner-data:/tmp/runner/work
    restart: always