apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "cfe70504-d7c1-4359-8f75-11500b7f45ea"
    keyvaultName: "kv-andrii"
    cloudName: "AzurePublicCloud"
    objects:  |
      array:
        - |
          objectName: DatabasePassword
          objectType: secret
          objectVersion: ""
    tenantId: "943707bc-becc-4d25-a039-78c22cbc7fc3" # FIXED: Must explicitly declare the Tenant ID
  secretObjects:
  - secretName: db-secret
    type: Opaque
    data:
    - objectName: DatabasePassword
      key: db-password