apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: guestbook
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "8c48b454-fecc-4a0e-89e3-b73a21304444"
    keyvaultName: "kv-andrii-dev"
    cloudName: "AzurePublicCloud"
    objects:  |
      array:
        - |
          objectName: DatabasePassword
          objectType: secret
          objectVersion: ""
    tenantId: "943707bc-becc-4d25-a039-78c22cbc7fc3" # FIXED: Must explicitly declare the Tenant ID
  secretObjects:
  - secretName: db-secret
    type: Opaque
    data:
    - objectName: DatabasePassword
      key: db-password