name: Terraform Apply

on:
  push:
    branches: [main]
    paths:
    #  - 'envs/dev/**'
      - '**/*.tf'
      - 'envs/**/*.tfvars'
      - 'envs/**/*.hcl'
      - '.github/workflows/terraform-*.yml'

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: [self-hosted, Linux, ARM64]
    environment: dev   # для prod — environment: prod с required reviewers
    defaults:
      run:
        working-directory: envs/dev
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform apply -auto-approve